[2024-06-06T00:25:34.338+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T00:25:34.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-06T00:25:30.191271+00:00 [queued]>
[2024-06-06T00:25:34.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-06T00:25:30.191271+00:00 [queued]>
[2024-06-06T00:25:34.376+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-06T00:25:34.393+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-06 00:25:30.191271+00:00
[2024-06-06T00:25:34.399+0000] {standard_task_runner.py:63} INFO - Started process 3113 to run task
[2024-06-06T00:25:34.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-06T00:25:30.191271+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpivf_6lf9']
[2024-06-06T00:25:34.404+0000] {standard_task_runner.py:91} INFO - Job 156: Subtask crear_tabla_si_no_existe
[2024-06-06T00:25:34.448+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-06T00:25:30.191271+00:00 [running]> on host 167cb9f6b96a
[2024-06-06T00:25:34.542+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T00:25:30.191271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T00:25:30.191271+00:00'
[2024-06-06T00:25:34.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T00:25:34.552+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-06T00:25:34.553+0000] {weather_info_ETL.py:19} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-06T00:25:35.939+0000] {weather_info_ETL.py:28} INFO - Conectado a Redshift con éxito!
[2024-06-06T00:25:36.543+0000] {weather_info_ETL.py:68} INFO - Tabla creada con éxito en Redshift.
[2024-06-06T00:25:36.545+0000] {weather_info_ETL.py:75} INFO - Conexión a Redshift cerrada.
[2024-06-06T00:25:36.547+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T00:25:36.547+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T00:25:36.558+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-06T00:25:30.191271+00:00, execution_date=20240606T002530, start_date=20240606T002534, end_date=20240606T002536
[2024-06-06T00:25:36.592+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T00:25:36.614+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-06T00:25:36.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
