[2024-06-05T21:30:26.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T21:30:26.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:30:22.789062+00:00 [queued]>
[2024-06-05T21:30:26.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:30:22.789062+00:00 [queued]>
[2024-06-05T21:30:26.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T21:30:26.836+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-05 21:30:22.789062+00:00
[2024-06-05T21:30:26.843+0000] {standard_task_runner.py:63} INFO - Started process 393 to run task
[2024-06-05T21:30:26.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-05T21:30:22.789062+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmp1rrp8ioq']
[2024-06-05T21:30:26.849+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask crear_tabla_si_no_existe
[2024-06-05T21:30:26.910+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:30:22.789062+00:00 [running]> on host 167cb9f6b96a
[2024-06-05T21:30:27.039+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T21:30:22.789062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T21:30:22.789062+00:00'
[2024-06-05T21:30:27.042+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T21:30:27.055+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-05T21:30:27.055+0000] {weather_info_ETL.py:23} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-05T21:30:28.307+0000] {weather_info_ETL.py:32} INFO - Conectado a Redshift con éxito!
[2024-06-05T21:30:28.873+0000] {weather_info_ETL.py:73} INFO - Tabla creada con éxito en Redshift.
[2024-06-05T21:30:28.875+0000] {weather_info_ETL.py:80} INFO - Conexión a Redshift cerrada.
[2024-06-05T21:30:28.877+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T21:30:28.879+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T21:30:28.899+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-05T21:30:22.789062+00:00, execution_date=20240605T213022, start_date=20240605T213026, end_date=20240605T213028
[2024-06-05T21:30:28.950+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T21:30:28.990+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T21:30:28.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
