[2024-05-27T21:21:17.914+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T21:21:18.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [queued]>
[2024-05-27T21:21:18.088+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [queued]>
[2024-05-27T21:21:18.097+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-27T21:21:18.176+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): main> on 2024-05-21 08:00:00+00:00
[2024-05-27T21:21:18.193+0000] {standard_task_runner.py:63} INFO - Started process 674 to run task
[2024-05-27T21:21:18.249+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Preentrega3-fedebar', 'main', 'scheduled__2024-05-21T08:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_fedebar.py', '--cfg-path', '/tmp/tmp7q_91oa2']
[2024-05-27T21:21:18.277+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask main
[2024-05-27T21:21:18.530+0000] {task_command.py:426} INFO - Running <TaskInstance: Preentrega3-fedebar.main scheduled__2024-05-21T08:00:00+00:00 [running]> on host ab7b4a79fe7d
[2024-05-27T21:21:19.093+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='Preentrega3-fedebar' AIRFLOW_CTX_TASK_ID='main' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T08:00:00+00:00'
[2024-05-27T21:21:19.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T21:21:19.128+0000] {logging_mixin.py:188} INFO - Inicio: 2024-05-27 21:21:19.128305
[2024-05-27T21:21:19.257+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-05-27T21:21:20.548+0000] {logging_mixin.py:188} INFO - Conectado a Redshift con Ã©xito!
[2024-05-27T21:21:21.294+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T21:21:21.300+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_python_fedebar.py", line 68, in main
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
NameError: name 'requests_cache' is not defined
[2024-05-27T21:21:21.448+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Preentrega3-fedebar, task_id=main, run_id=scheduled__2024-05-21T08:00:00+00:00, execution_date=20240521T080000, start_date=20240527T212118, end_date=20240527T212121
[2024-05-27T21:21:21.551+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task main (name 'requests_cache' is not defined; 674)
[2024-05-27T21:21:21.638+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T21:21:21.726+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T21:21:21.736+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
