[2024-06-04T02:27:46.686+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T02:27:46.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:27:34.941637+00:00 [queued]>
[2024-06-04T02:27:46.721+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:27:34.941637+00:00 [queued]>
[2024-06-04T02:27:46.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T02:27:46.739+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-04 02:27:34.941637+00:00
[2024-06-04T02:27:46.751+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-04T02:27:34.941637+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpjzg2p1kl']
[2024-06-04T02:27:46.751+0000] {standard_task_runner.py:63} INFO - Started process 6949 to run task
[2024-06-04T02:27:46.753+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask crear_tabla_si_no_existe
[2024-06-04T02:27:46.837+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:27:34.941637+00:00 [running]> on host 167cb9f6b96a
[2024-06-04T02:27:46.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T02:27:34.941637+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T02:27:34.941637+00:00'
[2024-06-04T02:27:46.987+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T02:27:47.002+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-04T02:27:47.003+0000] {weather_info_ETL.py:19} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-04T02:27:50.916+0000] {weather_info_ETL.py:66} INFO - Tabla creada con éxito en Redshift.
[2024-06-04T02:27:50.917+0000] {weather_info_ETL.py:71} INFO - Conexión a Redshift cerrada.
[2024-06-04T02:27:50.918+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T02:27:50.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T02:27:50.928+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-04T02:27:34.941637+00:00, execution_date=20240604T022734, start_date=20240604T022746, end_date=20240604T022750
[2024-06-04T02:27:50.952+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T02:27:50.975+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-04T02:27:50.977+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
