[2024-06-04T00:08:50.381+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T00:08:50.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T00:08:34.272958+00:00 [queued]>
[2024-06-04T00:08:50.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T00:08:34.272958+00:00 [queued]>
[2024-06-04T00:08:50.410+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T00:08:50.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-04 00:08:34.272958+00:00
[2024-06-04T00:08:50.434+0000] {standard_task_runner.py:63} INFO - Started process 2551 to run task
[2024-06-04T00:08:50.438+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-04T00:08:34.272958+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmpzypbg5j3']
[2024-06-04T00:08:50.439+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask crear_tabla_si_no_existe
[2024-06-04T00:08:50.493+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T00:08:34.272958+00:00 [running]> on host 167cb9f6b96a
[2024-06-04T00:08:50.577+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:08:34.272958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T00:08:34.272958+00:00'
[2024-06-04T00:08:50.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T00:08:50.588+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-04T00:08:50.589+0000] {weather_info_ETL.py:16} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-04T00:08:52.713+0000] {weather_info_ETL.py:62} INFO - Tabla creada con éxito en Redshift.
[2024-06-04T00:08:52.715+0000] {weather_info_ETL.py:67} INFO - Conexión a Redshift cerrada.
[2024-06-04T00:08:52.716+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T00:08:52.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T00:08:52.729+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-04T00:08:34.272958+00:00, execution_date=20240604T000834, start_date=20240604T000850, end_date=20240604T000852
[2024-06-04T00:08:52.780+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T00:08:52.806+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-04T00:08:52.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
