[2024-06-04T02:31:26.333+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T02:31:26.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:31:18.725126+00:00 [queued]>
[2024-06-04T02:31:26.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:31:18.725126+00:00 [queued]>
[2024-06-04T02:31:26.366+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T02:31:26.384+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-04 02:31:18.725126+00:00
[2024-06-04T02:31:26.392+0000] {standard_task_runner.py:63} INFO - Started process 7097 to run task
[2024-06-04T02:31:26.395+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-04T02:31:18.725126+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmp5k41p39r']
[2024-06-04T02:31:26.397+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask crear_tabla_si_no_existe
[2024-06-04T02:31:26.446+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-04T02:31:18.725126+00:00 [running]> on host 167cb9f6b96a
[2024-06-04T02:31:26.539+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T02:31:18.725126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T02:31:18.725126+00:00'
[2024-06-04T02:31:26.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T02:31:26.549+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-04T02:31:26.549+0000] {weather_info_ETL.py:19} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-04T02:31:28.566+0000] {weather_info_ETL.py:66} INFO - Tabla creada con éxito en Redshift.
[2024-06-04T02:31:28.567+0000] {weather_info_ETL.py:71} INFO - Conexión a Redshift cerrada.
[2024-06-04T02:31:28.569+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T02:31:28.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T02:31:28.581+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-04T02:31:18.725126+00:00, execution_date=20240604T023118, start_date=20240604T023126, end_date=20240604T023128
[2024-06-04T02:31:28.620+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T02:31:28.630+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
