[2024-06-05T21:56:24.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T21:56:24.321+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:56:18.216641+00:00 [queued]>
[2024-06-05T21:56:24.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:56:18.216641+00:00 [queued]>
[2024-06-05T21:56:24.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T21:56:24.351+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): crear_tabla_si_no_existe> on 2024-06-05 21:56:18.216641+00:00
[2024-06-05T21:56:24.357+0000] {standard_task_runner.py:63} INFO - Started process 1438 to run task
[2024-06-05T21:56:24.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'crear_tabla_si_no_existe', 'manual__2024-06-05T21:56:18.216641+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/dag_entregable_fedebar.py', '--cfg-path', '/tmp/tmp865id9vt']
[2024-06-05T21:56:24.363+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask crear_tabla_si_no_existe
[2024-06-05T21:56:24.419+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.crear_tabla_si_no_existe manual__2024-06-05T21:56:18.216641+00:00 [running]> on host 167cb9f6b96a
[2024-06-05T21:56:24.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FedeBar' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='crear_tabla_si_no_existe' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T21:56:18.216641+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T21:56:18.216641+00:00'
[2024-06-05T21:56:24.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T21:56:24.530+0000] {base.py:84} INFO - Using connection ID 'coder-redshift-fede' for task execution.
[2024-06-05T21:56:24.531+0000] {weather_info_ETL.py:23} INFO - Conectando a Redshift en data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
[2024-06-05T21:56:25.683+0000] {weather_info_ETL.py:32} INFO - Conectado a Redshift con éxito!
[2024-06-05T21:56:26.192+0000] {weather_info_ETL.py:73} INFO - Tabla creada con éxito en Redshift.
[2024-06-05T21:56:26.194+0000] {weather_info_ETL.py:80} INFO - Conexión a Redshift cerrada.
[2024-06-05T21:56:26.201+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T21:56:26.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T21:56:26.219+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ingestion_data, task_id=crear_tabla_si_no_existe, run_id=manual__2024-06-05T21:56:18.216641+00:00, execution_date=20240605T215618, start_date=20240605T215624, end_date=20240605T215626
[2024-06-05T21:56:26.305+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T21:56:26.364+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T21:56:26.369+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
